import matplotlib.pyplot as plt
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import os
import glob
import seaborn as sns
plt.style.use('seaborn-deep')
FILE_FORMAT = "../input/train_1/event000001000-{}.csv"
truth = pd.read_csv(FILE_FORMAT.format("truth"))
hits = pd.read_csv(FILE_FORMAT.format("hits"))
particles = pd.read_csv(FILE_FORMAT.format("particles"))
cells = pd.read_csv(FILE_FORMAT.format("cells"))
cellagg = cells.groupby("hit_id").agg({"value" : ["sum", "count"]})
cellagg.columns = cellagg.columns.droplevel()
cellagg.reset_index(inplace=True)
cellagg.columns = ["hit_id", "cell_sum", "cell_count"]
hits = pd.merge(hits, cellagg, on="hit_id")
truth['theta'] = np.degrees(np.arctan2(np.sqrt(truth.tpy.values ** 2 + truth.tpx.values ** 2), truth.tpz.values))
truth['phi'] = np.degrees(np.arctan2(truth.tpy.values, truth.tpx.values))
hits = pd.merge(hits, truth, on="hit_id")
plt.figure(figsize=(18,6))
plt.subplot(121)
buckets = np.arange(60)
plt.hist(hits.query("weight==0")["cell_count"].values, label="spurious", alpha=.5, normed=True, bins=buckets)
plt.hist(hits.query("weight>0")["cell_count"].values, label="real", alpha=.5, normed=True, bins=buckets)
plt.xlabel("cell count")
plt.grid()
plt.legend()
plt.subplot(122)
buckets = np.linspace(0, 10, 100)
plt.hist(hits.query("weight==0")["cell_sum"].values, label="spurious", alpha=.5, normed=True, bins=buckets)
plt.hist(hits.query("weight>0")["cell_sum"].values, label="real", alpha=.5, normed=True, bins=buckets)
plt.xlabel("cell value sum")
plt.grid()
_ = plt.legend()
for volume_id in sorted(set(hits.volume_id.values)):
    plt.figure(figsize=(18,6))
    plt.suptitle("Volume {}".format(volume_id))
    plt.subplot(121)
    buckets = np.arange(60)
    plt.hist(hits.query("(volume_id=={}) and (weight==0)".format(volume_id))["cell_count"].values, label="spurious", alpha=.5, normed=True, bins=buckets)
    plt.hist(hits.query("(volume_id=={}) and (weight>0)".format(volume_id))["cell_count"].values, label="real", alpha=.5, normed=True, bins=buckets)
    plt.xlabel("cell count")
    plt.grid()
    plt.legend()
    plt.subplot(122)
    buckets = np.linspace(0, 10, 100)
    plt.hist(hits.query("(volume_id=={}) and (weight==0)".format(volume_id))["cell_sum"].values, label="spurious", alpha=.5, normed=True, bins=buckets)
    plt.hist(hits.query("(volume_id=={}) and (weight>0)".format(volume_id))["cell_sum"].values, label="real", alpha=.5, normed=True, bins=buckets)
    plt.xlabel("cell value sum")
    plt.grid()
    _ = plt.legend()
    plt.show()
plt.figure(figsize=(18,6))
buckets = np.arange(60)
for volume_id in sorted(set(hits.volume_id.values)):
    plt.hist(hits.query("(volume_id=={}) and (weight==0)".format(volume_id))["cell_count"].values, label=str(volume_id), alpha=.5, normed=True, bins=buckets)
plt.xlabel("cell count")
plt.grid()
_ = plt.legend(title="volume")
plt.figure(figsize=(18,6))
buckets = np.arange(60)
for layer_id in sorted(set(hits.query("volume_id==8").layer_id.values)):
    plt.hist(hits.query("(volume_id==8) and (layer_id=={}) and (weight==0)".format(layer_id))["cell_count"].values, label=str(layer_id), alpha=.5, normed=True, bins=buckets)
plt.xlabel("cell count")
plt.grid()
_ = plt.legend(title="layer")
plt.figure(figsize=(18, 12))
buckets = np.arange(181)
for cnt in range(1, 10):
    plt.hist(hits.query("(weight > 0) and (cell_count == {})".format(cnt)).theta.values, normed=True, alpha=.5, label=str(cnt), bins=buckets)
plt.hist(hits.query("(weight > 0) and (cell_count > 9)").theta.values, normed=True, alpha=.25, label=">9", bins=buckets, fc='k')
plt.legend(title="cell count")
_ = plt.xlabel("theta")
for vol in sorted(set(hits.volume_id.values)):
    plt.figure(figsize=(18, 12))
    plt.title("Volume {}".format(vol))
    buckets = np.arange(181)
    for cnt in range(1, 10):
        plt.hist(hits.query("(weight > 0) and (cell_count == {} and (volume_id == {}))".format(cnt, vol)).theta.values, normed=True, alpha=.5, label=str(cnt), bins=buckets)
    plt.hist(hits.query("(weight > 0) and (cell_count > 9) and (volume_id == {})".format(vol)).theta.values, normed=True, alpha=.25, label=">9", bins=buckets, fc='k')
    plt.legend(title="cell count")
    plt.xlabel("theta")
    plt.show()
plt.figure(figsize=(18, 12))
buckets = np.arange(-180, 181)
for cnt in range(1, 10):
    plt.hist(hits.query("(weight > 0) and (cell_count == {})".format(cnt)).phi.values, normed=True, alpha=.5, label=str(cnt), bins=buckets)
plt.hist(hits.query("(weight > 0) and (cell_count > 9)").phi.values, normed=True, alpha=.25, label=">9", bins=buckets, fc='k')
plt.xlabel("phi")
_ = plt.legend(title="cell count")